# Generated by Django 4.1.3 on 2022-12-01 12:23

from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=11, verbose_name='phone')),
                ('provider_code', models.IntegerField(verbose_name='provider code')),
                ('tag', models.CharField(max_length=50, verbose_name='tag')),
                ('tz', timezone_field.fields.TimeZoneField(use_pytz=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'notice_client',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_at', models.DateTimeField(verbose_name='start at')),
                ('msg', models.CharField(max_length=200, verbose_name='message')),
                ('tag', models.CharField(max_length=50, verbose_name='tag')),
                ('stop_at', models.DateTimeField(verbose_name='stop at')),
            ],
            options={
                'verbose_name': 'Mailing',
                'verbose_name_plural': 'Mailings',
                'db_table': 'notice_mailing',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(verbose_name='created at')),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('canceled', 'Canceled')], max_length=50, verbose_name='status')),
                ('cliend', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notice.client', verbose_name='client')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notice.mailing', verbose_name='mailing')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'notice_message',
            },
        ),
    ]
