# Generated by Django 4.1.3 on 2022-12-01 12:28

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tz',
            field=timezone_field.fields.TimeZoneField(use_pytz=False),
        ),
    ]
