# Generated by Django 4.1.3 on 2022-12-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='tag name')),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='tag',
        ),
        migrations.AddField(
            model_name='client',
            name='tag',
            field=models.ManyToManyField(to='notice.tag'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='tag',
            field=models.ManyToManyField(to='notice.tag'),
        ),
    ]
