# Generated by Django 4.1.3 on 2022-12-06 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='client_id',
            new_name='client',
        ),
    ]
