# Generated by Django 4.1.3 on 2022-12-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_rename_client_id_message_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('sended', 'Success'), ('error', 'Error'), ('cancelled', 'Canceled')], default='created', max_length=50, verbose_name='status'),
        ),
    ]
